const districts = [
  "Bagerhat",
  "Bandarban",
  "Barguna",
  "Barisal",
  "Bhola",
  "Bogra",
  "Brahmanbaria",
  "Chandpur",
  "Chittagong",
  "Chuadanga",
  "Comilla",
  "Coxs Bazar",
  "Dhaka",
  "Dinajpur",
  "Faridpur",
  "Feni",
  "Gaibandha",
  "Gazipur",
  "Gopalganj",
  "Habiganj",
  "Jaipurhat",
  "Jamalpur",
  "Jessore",
  "Jhenaidah",
  "Khagrachari",
  "Khulna",
  "Kishoreganj",
  "Kurigram",
  "Kushtia",
  "Lakshmipur",
  "Lalmonirhat",
  "Madaripur",
  "Magura",
  "Manikganj",
  "Moulvibazar",
  "Munshiganj",
  "Mymensingh",
  "Naogaon",
  "Narayanganj",
  "Narsingdi",
  "Natore",
  "Nawabganj",
  "Netrakona",
  "Nilphamari",
  "Noakhali",
  "Pabna",
  "Panchagarh",
  "Parbatty",
  "Patuakhali",
  "Pirojpur",
  "Rajbari",
  "Rajshahi",
  "Rangpur",
  "Satkhira",
  "Shariatpur",
  "Sherpur",
  "Sirajganj",
  "Sunamganj",
  "Sylhet",
  "Tangail",
  "Thakurgaon",
];

export const registerFieldData = [
  {
    name: "fullName",
    label: "Full name",
    required: true,
  },
  { name: "dateOfBirth", label: "Date of birth" },
  {
    name: "gender",
    label: "Gender",
    type: "select",
    options: ["Male", "Female"],
  },
  {
    name: "district",
    label: "District",
    type: "select",
    options: districts,
  },
  {
    name: "nid",
    label: "National ID",
  },
  {
    name: "regNumBMDC",
    label: "Registration Number (BMDC)",
  },
  {
    name: "doctorType",
    label: "Doctor Type",
    type: "select",
    options: ["Medical", "Dental", "Veterinary"],
  },
  {
    name: "mobile",
    label: "Mobile number",
    pattern: /^(\+?880|0)[1-9][0-9]{9}$/,
  },
  {
    name: "email",
    label: "Email",
    pattern: /^\w+([\.-]?\w+)*@\w+([\.-]?\w+)*(\.\w{2,3})+$/,
  },
  {
    name: "password",
    label: "Password",
  },
];
